spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tasktracker
      database: tasktracker

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    reactor.netty: INFO
